### ISSUE TITLE
Something's wrong with the wings.

### ISSUE THREAD

**Issue by pokedevotee11** [Gegy/Wearables#11]
When I am flying with the wings, the character appears upright. 
![minecraft 1 12 2 9_30_2017 5_09_40 pm](https://user-images.githubusercontent.com/32423933/31050469-e4b2f9dc-a607-11e7-812a-6ca29d9d97b5.png)

**Comment by Gegy** [comment]
Closing due to no response.

**Comment by GundunUkan** [comment]
Looks to me like you just haven't entered flight mode and are using the creative flying. Try holding down spacebar in survival.
