### ISSUE TITLE
Server crash - java.lang.NoSuchMethodError: net.minecraft.entity.passive.EntitySheep

### ISSUE THREAD

**Issue by ProsperCraft** [Gegy/Wearables#7]
https://gist.github.com/ProsperCraft/b2f9e635a9cd68a6f7ac484c41266fba

wearables-1.1.1

**Comment by Gegy** [comment]
For now, this can be fixed by removing CraftTweaker, if that's possible.

**Comment by ProsperCraft** [comment]
Will add Wearables back when its fixed :)  Thank you for looking at it.

**Comment by Gegy** [comment]
[Fixed](https://minecraft.curseforge.com/projects/wearables/files/2476510). :)

**Comment by ProsperCraft** [comment]
Thank you, added back and working.
