### ISSUE TITLE
Bug: Wings and Jetpack don't give custom model when used (1.12.1)

### ISSUE THREAD

**Issue by Akitori** [Gegy/Wearables#8]
Howdy! So for 1.12.1, the wings don't work properly (before your body would be facing like when using a elytra, that no longer is the case) Jetpacks have the same issue, but they were working fine in 1.12 (i tested it myself)

**Comment by Gegy** [comment]
Do you have LLibrary for 1.12.1 installed?

**Comment by Akitori** [comment]
Yeah that was my bad. sorry!
