### ISSUE TITLE
Armor Applied Twice?

### ISSUE THREAD

**Issue by Akitori** [Gegy/Wearables#9]
Not sure if this is my end, but armor is being applied twice with wearable gear. Ex: putting a diamond chestplate with wings should give me 4 full armor icons, but it gives me eight instead!

**Comment by Gegy** [comment]
Thanks for the report!. For future [reference](https://youtu.be/nwG4aJZ9hdU?t=9m20s)

**Comment by Akitori** [comment]
further note that might help, this was done on a smp server, just as a fyi.
